name: sobertrack_app
description: Un'app per monitorare il tasso alcolemico.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.5
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^21.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

# --- CONFIGURAZIONE ICONE ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  notification_icon:
    platforms:
      android: true
    image_path: "assets/images/logo_notifica.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  
  # --- ASSETS ---
  assets:
    - assets/images/